document.getElementById("date").min = new Date().toISOString().split("T")[0];
// Found this here: https://stackoverflow.com/questions/74585566/set-date-input-fields-minimum-date-to-today

var majors = ["Accounting",
"Agriculture",
"Anthropology",
"Area/Group Studies",
"Art &amp; Art History",
"Arts Administration",
"Aviation",
"Biology",
"Business",
"Chemistry",
"Communication",
"Computer Science",
"Construction",
"Criminal Justice",
"Cybersecurity",
"Dance",
"Data Science",
"Economics",
"Education",
"Engineering",
"English",
"Environmental Studies",
"Exercise Science",
"Family Life &amp; Human Development",
"Film",
"Finance",
"General Studies",
"Geography",
"Geology",
"Graphic Design",
"Health Sciences",
"History",
"Hospitality Management",
"Information Technology",
"Interdisciplinary Studies",
"Languages",
"Leadership",
"Library Media/School Library",
"Management",
"Marketing",
"Mathematics",
"Military Science",
"Music",
"Nursing",
"Nutrition",
"Outdoor Recreation",
"Philosophy",
"Physical Education",
"Physics",
"Political Science",
"Psychology",
"Public Administration",
"Secondary Education",
"Social Studies",
"Social Work",
"Sociology",
"Software Development",
"Sports",
"Theatre"]

var fNames = ["Ainslee",
"Alysa",
"Berrie",
"Cami",
"Deirdre",
"Devon",
"Dora",
"Elaina",
"Genia",
"Godiva",
"Jerrylee",
"Karyn",
"Nolana",
"Perrine",
"Rachel"]

var lNames = ["Cartmill",
"Cherrington",
"Ellington",
"Gascho",
"Hellums",
"Landesberg",
"Lehtonen",
"Mankins",
"Melchior",
"Molpus",
"Sangalli",
"Shehane",
"Stinebaugh",
"Willigar",
"Wiser"
]

var majorsel = document.getElementById("majors")
